CURRENT_VERSION_CODE = 2
CURRENT_VERSION_NAME = "2.0"

"""
Config Keys
"""
CONFIG_KEY_VERSION_CODE = "VERSION_CODE"
CONFIG_KEY_DATA_SOURCE = "DATA_SOURCE"
CONFIG_KEY_IS_MUTED = "IS_MUTED"
CONFIG_KEY_AUDIO_VOLUME = "AUDIO_VOLUME"
CONFIG_KEY_IS_STATIC_WALLPAPER = "IS_STATIC_WALLPAPER"
CONFIG_KEY_WALLPAPER_BLUR_R = "WALLPAPER_BLUR_R"
CONFIG_KEY_IS_DETECT_MAXIMIZED = "IS_DETECT_MAXIMIZED"
