from gi.repository import Gtk
from .app_config import TRANSLATE_CREDITS_URL
from .messages import (
    KAPITANO,
    STAY_SAFE_FROM_MALWARE,
    COMMUNITY_CONTRIBUTORS,
    MAIN_MENU,
    PREFERENCES,
    KEYBOARD_SHORTCUTS,
    ABOUT_KAPITANO,
)

APP_NAME = KAPITANO
APP_SUMMARY = STAY_SAFE_FROM_MALWARE
APP_TRANSLATOR_CREDITS = COMMUNITY_CONTRIBUTORS + TRANSLATE_CREDITS_URL

MENU_TOOLTIP_TEXT = MAIN_MENU
MENU_ITEMS = [
    (PREFERENCES, "app.preferences"),
    (KEYBOARD_SHORTCUTS, "app.shortcuts"),
    (ABOUT_KAPITANO, "app.about"),
]
