#!/usr/bin/env python3
import argparse
import time
import os

# Make sure that X11 is the backend. This makes sure Wayland reverts to XWayland.
os.environ['GDK_BACKEND'] = "x11"

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('-p', '--pause', type=int, default=0)
    args = parser.parse_args()
    time.sleep(args.pause)
    # Do import after the sleep. (if not SIGSEGV during autostart)
    from player import Player
    Player()
